### ISSUE TITLE
Defaults

### ISSUE THREAD

**Issue by apoapostolov** [AnthonyEdmonds/token-aura-ring#10]
Please add a button to record changed settings as a default, with option for defaults for linked and unlinked actors separately.

**Comment by AnthonyEdmonds** [comment]
Token Auras are currently stored on the token alone. Are you suggesting that the aura be storable at the actor level?

**Comment by apoapostolov** [comment]
No I mean that it is possible to set things like color or thickness as default per linked (PCs) or unlinked (NPCs/enemies) and they don't need to be edited every time for each actor.

**Comment by AnthonyEdmonds** [comment]
I'm afraid I don't understand what you are after. You're welcome to clarify further, if you can provide more specific details.

**Comment by apoapostolov** [comment]
Hello. I want to have a set of parameters for color, border width etc. to be default when creating an aura.

**Comment by AnthonyEdmonds** [comment]
You want to override the global default, which is applied to all Tokens when a new Aura is created?
