### ISSUE TITLE
Functionality to convert aura abilities into Token Auras Rings

### ISSUE THREAD

**Issue by apoapostolov** [AnthonyEdmonds/token-aura-ring#11]
A button in Token Aura Ring UI in the Token HUD to scan the actor for any Aura abilities with Rule Element and convert them into Auras with the name of the Ability as name, and size based on the aura, and color based on type (offensive / defensive / etc.) dropdown int he aura feature.

**Comment by AnthonyEdmonds** [comment]
Token Aura Ring is a generic module, not made for any specific game system, and this sounds like something which would only work with one specific game system.

Unless you have a reference I can look at which shows these abilities and rules as core parts of Foundry, I don't think this can be done generically.
