### ISSUE TITLE
Just question - is this for PF2 only?

### ISSUE THREAD

**Issue by apoapostolov** [AnthonyEdmonds/token-aura-ring#12]
The way I see the current implementation, it feels like a successor to Token Auras which is system agnostic. Do you think this can be also usable for other systems without any PF2 specific functionality?

**Comment by AnthonyEdmonds** [comment]
There is nothing about this which is specific to any game system. I use it with the generic world building system myself.

**Comment by apoapostolov** [comment]
Thank you. I will be using it as a successor to Token Auras completely.
