### ISSUE TITLE
Feature request: option to "close" partial auras

### ISSUE THREAD

**Issue by Orionox** [AnthonyEdmonds/token-aura-ring#15]
it would be nice if we could close auras that are not fully around a token. 
![Screenshot 2024-08-14 104135](https://github.com/user-attachments/assets/70838edb-9988-41ee-9104-f92b226e8623)

**Comment by Orionox** [comment]
Would also be nice if we could fill in the aura with color if we wanted.

**Comment by AnthonyEdmonds** [comment]
The fill aspect was asked for in #9, and is on the way.

There's limited space in the UI for any more options, so I have been working on a UI overhaul as time permits, and as Foundry's murky documentation allows.

**Comment by AnthonyEdmonds** [comment]
This is now live with v2.0.0. Enjoy!
