### ISSUE TITLE
Non-breaking errors in console

### ISSUE THREAD

**Issue by TimorSol** [AnthonyEdmonds/token-aura-ring#17]
Hey! 
I see a console error being thrown pretty consistently for The Aura Ring module. It's not breaking and I think it actually might be caused by another module, but I wanted to give info about this one so or so. 

![obraz](https://github.com/user-attachments/assets/bf12a73d-a385-4a8e-babd-5c2bb250e93e)

I'm assuming it's actually connected with a different module because of the error below, which is connected with elevation ruler and which usually pops up in the same time:

![obraz](https://github.com/user-attachments/assets/9501ea9e-f6c1-4f97-b56c-82fa7d42c5e3)

In case this is a system issue, we are running this on 
Foundry V 12.331
Level Up: Advanced 5th Edition 0.19.24

**Comment by AnthonyEdmonds** [comment]
See whether it still happens with the new v2.0.0. You can re-open the ticket if it does.

**Comment by TimorSol** [comment]
surprisingly, yes :O 

![obraz](https://github.com/user-attachments/assets/cd66e8e8-8f27-423d-86c7-864f645fd0ef)

**Comment by AnthonyEdmonds** [comment]
Looks like whatever the other module is doing, they have tied into the refresh token hook to do some logic, but that hook doesn't pass a simpleToken per the base Foundry API. I can add a check on my end to make sure that it onlt tries to apply logic to SimpleTokens.

**Comment by AnthonyEdmonds** [comment]
See whether it still happens with the new v2.1.0. You can re-open the ticket if it does.
