### ISSUE TITLE
Feature Request: Exposed API for being able to quickly edit rings using macros/code

### ISSUE THREAD

**Issue by Deyzeria** [AnthonyEdmonds/token-aura-ring#20]
In my specific case, sometimes I need to instantly change a Direction of an angled ring, and going inside setting and fumbling to rotate it +90 degrees is a bit of a hassle. Doesn't need to be that in-depth, but being able to, on the fly, get existing values and edit them would be incredible.

Thanks for the module <3

**Comment by ronin-seven** [comment]
+1 to this request.

I'm currently on v10 using Token Auras and when I update to v12 (or v13), I would like to migrate to this module and absolutely need an API to dynamically create rings when certain spells are cast.

**Comment by AnthonyEdmonds** [comment]
It is coming in the next release.
