### ISSUE TITLE
Request: Add On/Off Toggle

### ISSUE THREAD

**Issue by kajishun** [AnthonyEdmonds/token-aura-ring#23]
Please add a toggle to be able to turn on/off individual auras. It would be great to be able build auras then enable or disable based on circumstances or need. Thanks!

**Comment by AnthonyEdmonds** [comment]
I presume you are looking for something more binary than changing the "Visible to" property?

I'll see about adding a show/hide toggle to the configuration page.

In the meantime, you could use the new API to make custom macros

**Comment by kajishun** [comment]
Ah, I will also give the visible to option a go. Yes, mainly looking for an
on/off binary option.

**Comment by AnthonyEdmonds** [comment]
Toggle button is now available in 2.3.0
