### ISSUE TITLE
No rings are shown after updating to 2.1.0

### ISSUE THREAD

**Issue by nschoenwald** [AnthonyEdmonds/token-aura-ring#29]
Foundry V12 latest and DnD5e 4.1.1

Disabled other modules for testing with Find the Culprit

<img width="1273" alt="image" src="https://github.com/user-attachments/assets/713db587-2251-4d20-9a7d-97482f5340ef">

**Comment by Deyzeria** [comment]
Completely same issue. Have tried the following-
Forge server from Firefox, Chrome and Foundry lightweight client.
Local Foundry.

Tried adding a new aura, deleting all existing auras, and loading in a completely new game, where I have never used the module before.

**Comment by AnthonyEdmonds** [comment]
Hmm. That isn't much for me to work with.

Locally everything is working fine on my end... could it be that the DND5e module isn't using SimpleTokenDocuments, and my fix for AuraRing trying to render classes which aren't that, is what's going on here?

It's somewhere to start, at least.

**Comment by AnthonyEdmonds** [comment]
Hmm. That isn't much for me to work with.

Locally everything is working fine on my end... could it be that the DND5e module isn't using SimpleTokenDocuments, and my fix for AuraRing trying to render classes which aren't that, is what's going on here?

It's somewhere to start, at least.

**Comment by nschoenwald** [comment]
I don't think the second one is relevant, but I'm not a developer so I wanted to share both console errors I have when loading a scene with actors that should have token rings.

When dragging a token that should have rings to the scene, I don't get a console error.

<img width="405" alt="image" src="https://github.com/user-attachments/assets/14210f53-fa31-44c9-93d5-b522c552b54a">
<img width="414" alt="image" src="https://github.com/user-attachments/assets/319740b2-cebc-46f2-a7f2-a94c3d419ccc">

**Comment by AnthonyEdmonds** [comment]
Try version 2.2.1. I don't use anything other than the simple world building system, so hopefully they all extend the base Token / TokenDocument under the hood.

**Comment by Deyzeria** [comment]
Seems to work on dnd5e! 
![image](https://github.com/user-attachments/assets/3464f3a8-14d1-41aa-855c-41a0e3e250bf)

**Comment by AnthonyEdmonds** [comment]
Let's just hope that hasn't reintroduced the issue the other person was having with auras being rendered on non-token objects.
