### ISSUE TITLE
module.json reflects minimum Foundry version to 11 but the module is not shown beyond 1.3.1

### ISSUE THREAD

**Issue by LeCuay** [AnthonyEdmonds/token-aura-ring#30]
# Summary

So at first I thought that was the last version available for Foundry v11 (_I'm playing Pathfinder 1e_) but after checking the `module.json` seems to be that minimum is 11 not 12 but that version is not downloadable from Foundry packages.

**Comment by AnthonyEdmonds** [comment]
So it does. I have corrected that now and it will be properly reflected going forward.

Version 12 is required, as I only test in the latest version.
