### ISSUE TITLE
Feature Request: Expose API in the global environment within the game so that it is actually can be interacted with for macros, without importing directly.

### ISSUE THREAD

**Issue by Deyzeria** [AnthonyEdmonds/token-aura-ring#32]
While what is mentioned seems very nice, I can't seem to find the ways of accessing the newly exposed API. Can you maybe provide examples of how to access it - because as far as I can see it from the code, it is only exported? Because if yes, maybe you can expose it within global environment within the game, so it could be used in macros, etc.

Thank you.

**Comment by Deyzeria** [comment]
Just for example, something as simple as this already makes the api be exposed and allow it to be interacted with-
![image](https://github.com/user-attachments/assets/75956fa9-7d71-4e48-84df-eb347f4fbb0e)
![image](https://github.com/user-attachments/assets/6a01f765-bc6d-4e82-a21b-0da2c3df9dac)

**Comment by Deyzeria** [comment]
![image](https://github.com/user-attachments/assets/1a9a9309-41db-41ad-892c-dbc9184cc094)

**Comment by AnthonyEdmonds** [comment]
An oversight on my part. The API should be available at TokenAuraRing.

I have updated the documentation with an example.
