### ISSUE TITLE
API Bug- Aura id is sometimes a number, sometimes a string

### ISSUE THREAD

**Issue by Deyzeria** [AnthonyEdmonds/token-aura-ring#34]
When creating an aura with AuraRingApi.new(), it makes id always be `0` as a number. When attempting to get the aura using getAuraRingIndex, it breaks, because it transforms id in the request to be a string instead. Opening configuration manually and saving makes every aura have their id be a string, therefore getAuraRingIndex actually works.

**Comment by AnthonyEdmonds** [comment]
Yeah, somewhere in the middle of development I forgot that `for ... in` doesn't work properly for arrays, but didn't go back to correct the uses I had already written.

**Comment by AnthonyEdmonds** [comment]
Give 2.1.3 a go, I have amended the various typing and looping issues.

**Comment by Deyzeria** [comment]
Haven't encountered a bug, so for now I agree that this can be closed.
