### ISSUE TITLE
I had to reinstall to get 2.1.2 to work

### ISSUE THREAD

**Issue by nschoenwald** [AnthonyEdmonds/token-aura-ring#35]
After updating, I had this error:

<img width="623" alt="image" src="https://github.com/user-attachments/assets/950a9635-bcae-4f13-a93c-a24e3189d751">

After deleting and reinstalling the module, it works, but maybe there needs be some migrations script or something so this doesn't occur for other users.

**Comment by AnthonyEdmonds** [comment]
Just a temporary blip. Foundry doesn't handle retagging very well.
