### ISSUE TITLE
Question - How to set an aura only visible for the player that own the token ?

### ISSUE THREAD

**Issue by Arnok13** [AnthonyEdmonds/token-aura-ring#38]
Hi,

i haven't found this on the documentation, but is it possible to have an aura only visible for the player that own the token (and the Game Master obviously).

Thanks for any answers.

Arnok

**Comment by AnthonyEdmonds** [comment]
Aura Rings are visible to anyone that can see them based on line of sight and their system role.

I suppose it should be possible to make it so that an Aura Ring would only display to the owner of a token, if that's what you are after.

**Comment by AnthonyEdmonds** [comment]
The "Only show for owner?" option has been added in version 2.4.0

**Comment by Arnok13** [comment]
thanks a lot !
