### ISSUE TITLE
Feature Request: Add setting to show aura ring only on hover 

### ISSUE THREAD

**Issue by Satosan111** [AnthonyEdmonds/token-aura-ring#39]
Please add an option for aura ring to be visible only when the cursor is hovered over token by a person who has permission to see the ring.
Thank you for your mod!

**Comment by AnthonyEdmonds** [comment]
An interesting concept, I can see how it could be implemented.

**Comment by Satosan111** [comment]
Something similar is implemented in Bar Brawl mod (https://foundryvtt.com/packages/barbrawl) for unit resource bars. It might hugely improve visibility of scenes with multiple actors, as it would allow to quickly switch between aura indicators by hovering cursor over tokens.

**Comment by AnthonyEdmonds** [comment]
The option to only showing auras on hover has been added in 2.3.0

**Comment by Satosan111** [comment]
This is great. Thank you!
