### ISSUE TITLE
The manifest link is wrong

### ISSUE THREAD

**Issue by surestart** [AnthonyEdmonds/token-aura-ring#7]
We can't install the module because the manifest link points to the website rather than the module .json

**Comment by xaukael** [comment]
best to use the raw 
like: https://raw.githubusercontent.com/AnthonyEdmonds/token-aura-ring/1.3.0/module.json

**Comment by AnthonyEdmonds** [comment]
Try it now

**Comment by surestart** [comment]
Worked! Thank you.
