### ISSUE TITLE
Style Support - Background (Transparency) 

### ISSUE THREAD

**Issue by apoapostolov** [AnthonyEdmonds/token-aura-ring#9]
Please add support for background with level of transparency (0.1 or 0.05 as default). This is one of the few remaining visual features of Token Auras that miss in this mod. Thanks!

We discussed this in Dorako channel on Discord and he quickly hacked a method to do it

![image](https://github.com/AnthonyEdmonds/token-aura-ring/assets/4083812/73a74baf-2850-48cc-9c1a-5f1030702dc0)

```
this.pixiGraphics.beginFill(Color.from(aura.colour), aura.opacity / 3);
this.pixiGraphics.drawEllipse(auraX, auraY, auraRadius, auraRadius);
this.pixiGraphics.endFill();
```

**Comment by AnthonyEdmonds** [comment]
Agreed, it is indeed trivial since it is all canvas paths.

I initially made this library because I didn't like the solid fill and would rather have a ring, however if other people want it I'll see what I can do.

**Comment by apoapostolov** [comment]
It is very pleasant when used at a very low transparency level (0.1 or 0.05 is my favourite). It does not look good when colored or when higher than that. So a default could be set to a very low transparency, if turned on.

**Comment by AnthonyEdmonds** [comment]
There's limited space in the UI for any more options, so I have been working on a UI overhaul as time permits, and as Foundry's murky documentation allows.

**Comment by AnthonyEdmonds** [comment]
This is now live with v2.0.0. Enjoy!

**Comment by apoapostolov** [comment]
Thank you very much!
